services:
  - type: web
    name: tomato-leaf-disease-classification
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    dockerfilePath: ./tomato_leaf_disease/Dockerfile